name: vendas-online
services:
  - name: web
    # Força o uso do Dockerfile
    dockerfile_path: Dockerfile
    source_dir: /

    # Porta onde a aplicação vai rodar (8080)
    http_port: 8080

    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # Configurações de recursos
    instance_count: 1
    instance_size_slug: basic-xxs

    # Variáveis de ambiente (adicione aqui se necessário)
    envs:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
